<?php
namespace SeanMorris\ClonesNBarrels\Theme;
class Theme extends \SeanMorris\Theme\Theme
{
	public static $view = [
			'SeanMorris\Ids\Model' => [
				'single' => 'SeanMorris\PressKit\Theme\Austere\Model'
				, 'list' => 'SeanMorris\PressKit\Theme\Austere\ModelGrid'
			]
			, 'SeanMorris\ClonesNBarrels\Map' => [
				'single' => 'SeanMorris\ClonesNBarrels\View\Play'
			]
			, 'stack' => 'SeanMorris\PressKit\Theme\Austere\Page'
			, 'css' => ['SeanMorris/ClonesNBarrels/Css/main.css']
			, 'js' =>[
				'SeanMorris/ClonesNBarrels/Js/jquery-1.11.2.min.js'
				, 'SeanMorris/ClonesNBarrels/Js/ThirdParty/Class.js'
				, 'SeanMorris/ClonesNBarrels/Js/ThirdParty/FileSaver.js'
				, 'SeanMorris/ClonesNBarrels/Js/ThirdParty/Cookie.js'
				, 'SeanMorris/ClonesNBarrels/Js/Menu/Menu.js'
				, 'SeanMorris/ClonesNBarrels/Js/Menu/MusicSubmenu.js'
				, 'SeanMorris/ClonesNBarrels/Js/Menu/MainMenu.js'
				, 'SeanMorris/ClonesNBarrels/Js/Menu/Dialog.js'
				, 'SeanMorris/ClonesNBarrels/Js/Menu/PauseMenu.js'
				, 'SeanMorris/ClonesNBarrels/Js/Menu/DialogMenu.js'
				, 'SeanMorris/ClonesNBarrels/Js/Menu/ContinueMenu.js'
				, 'SeanMorris/ClonesNBarrels/Js/Menu/SaveSubmenu.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Actor.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Bindable.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Character.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Damageable.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Trigger.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Triggerable.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Projectile.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Bullet.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/FloorActor.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Sprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Primitives/Spritesheet.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/PortalSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/FireSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/ButtonSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/BarrelSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/BoxSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/LavaSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/ComputerSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/SandbagSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/LaserBeamSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/NullSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/TriggerSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/PlayerCorpseSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/IceBlockSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/PlayerSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/BloodStainSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/WoodBoxSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/BlastMarkSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/ButtonActivatedSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/BarrierSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/PitSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/AngleSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/CheeseSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/BarrelHoleSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/DoorSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/BubbleSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/WarpSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/BoxesSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/RockSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/HealthSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/SentinelSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Sprites/Free/SentinelCorpseSprite.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/Bgm.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/MenuState.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/TitleState.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/ClickVector.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/DialogMenuState.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/State.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/TitleScreen.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/MainState.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/Message.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/Editor.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/DialogState.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/Storable.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/SaveState.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/Map.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/SaveState.js'
				, 'SeanMorris/ClonesNBarrels/Js/Game/Game.js'
				, 'SeanMorris/ClonesNBarrels/Js/Support/ImageCache.js'
				, 'SeanMorris/ClonesNBarrels/Js/Viewport/Pane.js'
				, 'SeanMorris/ClonesNBarrels/Js/Viewport/Viewport.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/IceBlock.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Box.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/HollowBox.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/BlastMark.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Pit.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Angle.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/WoodBox.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Sandbag.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/SignPost.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/PartySpawner.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/BloodStain.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Cheese.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/CloneMachine.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/AbstractTriggerableAny.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Boxes.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Barrier.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Portal.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Item.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Warp.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/PlasmaBall.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Wanderer.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Bubble.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Player.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Lava.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/AbstractTriggerableAllAtOnce.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/PolyWall.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/GasTrap.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Button.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Corpse.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/BarrelHole.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Barrel.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Door.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/PlayerClone.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/LaserBeam.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Rock.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Health.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Wanderer.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Sentinel.js'
				, 'SeanMorris/ClonesNBarrels/Js/Objects/Explosion.js'
				, 'SeanMorris/ClonesNBarrels/Js/World/World.js'
				, 'SeanMorris/ClonesNBarrels/Js/World/MapSet.js'
				, 'SeanMorris/ClonesNBarrels/Js/World/Maps/basement_001.js'
				, 'SeanMorris/ClonesNBarrels/Js/World/Maps/surface_001.js'
				, 'SeanMorris/ClonesNBarrels/Js/World/Tile.js'
				, 'SeanMorris/ClonesNBarrels/Js/World/Map.js'
				, 'SeanMorris/ClonesNBarrels/Js/Init.js'
			]
		],
		$themes = [
			'SeanMorris\PressKit\Theme\Austere\Theme'
		]
	;
}